Repository hashgraph/hedera-smart-contracts, pull requests merged in 2022-11, with the labels that each got.

#125 Complete HIP 206 transfer test cases
  .github/workflows/test-workflow.yml
  .github/workflows/tests.yml
  contracts/hts-precompile/HederaTokenService.sol
  contracts/hts-precompile/examples/token-transfer/TokenTransferContract.sol
  package-lock.json
  package.json
  test/hts-precompile/token-create/tokenCreateContract.js
  test/hts-precompile/token-transfer/tokenTransferContract.js
Labels: enhancement, P1, Limechain

#126 Resolve coupling and clean contracts
  contracts/hts-precompile/ExpiryHelper.sol
  contracts/hts-precompile/FeeHelper.sol
  contracts/hts-precompile/HederaResponseCodes.sol
  contracts/hts-precompile/HederaTokenService.sol
  contracts/hts-precompile/KeyHelper.sol
  contracts/hts-precompile/examples/token-create/TokenCreateContract.sol
  contracts/hts-precompile/examples/token-manage/TokenManagementContract.sol
  contracts/hts-precompile/examples/token-query/TokenQueryContract.sol
  contracts/hts-precompile/examples/token-transfer/TokenTransferContract.sol
Labels: enhancement, P2, Limechain

#127 Critical HTS functions marked external
  contracts/hts-precompile/HederaTokenService.sol
  contracts/hts-precompile/examples/token-create/TokenCreateContract.sol
  contracts/hts-precompile/examples/token-manage/TokenManagementContract.sol
  contracts/hts-precompile/examples/token-query/TokenQueryContract.sol
  test/hts-precompile/erc-721/ERC721Contract.js
  test/hts-precompile/utils.js
Labels: P2, Limechain

#134 Tests to show system HTS contract transferFrom does not work without approval
  test/hts-precompile/token-transfer/tokenTransferContract.js
Labels: enhancement, P2

#137 Add System Contract ABI JSON files
  .gitignore
  artifacts/contracts/exchange-rate-precompile/ExchangeRatePrecompile.sol/ExchangeRatePrecompile.json
  artifacts/contracts/exchange-rate-precompile/IExchangeRate.sol/IExchangeRate.json
  artifacts/contracts/exchange-rate-precompile/SelfFunding.sol/SelfFunding.json
  artifacts/contracts/hts-precompile/ExpiryHelper.sol/ExpiryHelper.json
  artifacts/contracts/hts-precompile/FeeHelper.sol/FeeHelper.json
  artifacts/contracts/hts-precompile/HederaResponseCodes.sol/HederaResponseCodes.json
  artifacts/contracts/hts-precompile/HederaTokenService.sol/HederaTokenService.json
  artifacts/contracts/hts-precompile/IHederaTokenService.sol/IHederaTokenService.json
  artifacts/contracts/hts-precompile/KeyHelper.sol/Bits.json
  artifacts/contracts/hts-precompile/KeyHelper.sol/KeyHelper.json
  artifacts/contracts/hts-precompile/examples/erc-20/ERC20Contract.sol/ERC20Contract.json
  artifacts/contracts/hts-precompile/examples/erc-721/ERC721Contract.sol/ERC721Contract.json
  artifacts/contracts/hts-precompile/examples/token-create/TokenCreateContract.sol/TokenCreateContract.json
  artifacts/contracts/hts-precompile/examples/token-manage/TokenManagementContract.sol/TokenManagementContract.json
  artifacts/contracts/hts-precompile/examples/token-query/TokenQueryContract.sol/TokenQueryContract.json
  artifacts/contracts/hts-precompile/examples/token-transfer/TokenTransferContract.sol/TokenTransferContract.json
  artifacts/contracts/safe-hts-precompile/HederaResponseCodes.sol/HederaResponseCodes.json
  artifacts/contracts/safe-hts-precompile/SafeHTS.sol/SafeHTS.json
  artifacts/contracts/safe-hts-precompile/SafeOperations.sol/SafeOperations.json
  artifacts/contracts/util-precompile/IPrngSystemContract.sol/IPrngSystemContract.json
  artifacts/contracts/util-precompile/PrngSystemContract.sol/PrngSystemContract.json
Labels: enhancement, P2
