Repository hashgraph/hedera-smart-contracts, pull requests merged in 2022-10, with the labels that each got.

#72 Add ERC 20 example contract to highlight HIP 218
  .gitignore
  contracts/hts-precompile/erc-20/ERC20Contract.sol
  test/hts-precompile/erc-20/ERC20Contract.js
  test/hts-precompile/utils.js
Labels: enhancement, P2, Limechain

#77 Update HederaResponseCodes.sol
  contracts/hts-precompile/HederaResponseCodes.sol
Labels: enhancement, P2, Limechain

#76 Test CI
  .github/workflows/test.yml
  hardhat.config.js
  test/safe-hts-precompile/SafeHTS.js
Labels: enhancement, P2, Limechain

#87 Update README with contribution details
  README.md
Labels: documentation, P1

#90 Bump 0.3.0-SNAPSHOT
  package.json
Labels: enhancement

#91 Bump 0.2.0-rc1
  README.md
  package.json
Labels: enhancement

#92 Add npm artifact
  .github/workflows/release-production.yml
Labels: enhancement

#98 Bump 0.2
  package.json
Labels: enhancement

#114 Refactor example token contracts
  contracts/hts-precompile/HederaTokenService.sol
  contracts/hts-precompile/TokenCreate.sol
  contracts/hts-precompile/examples/token-create/TokenCreateContract.sol
  contracts/hts-precompile/examples/token-manage/TokenManagementContract.sol
  contracts/hts-precompile/examples/token-query/TokenQueryContract.sol
  contracts/hts-precompile/examples/token-transfer/TokenTransferContract.sol
  package.json
  test/hts-precompile/erc-721/ERC721Contract.js
  test/hts-precompile/token-create/tokenCreateContract.js
  test/hts-precompile/utils.js
  test/safe-hts-precompile/SafeHTS.js
Labels: enhancement, P1, Limechain

#117 Add TokenQueryContract test cases
  .github/workflows/test-workflow.yml
  .github/workflows/tests.yml
  package-lock.json
  package.json
  test/hts-precompile/token-query/tokenQueryContract.js
  test/hts-precompile/utils.js
Labels: enhancement, P1, Limechain

#118 HIP 206 create functions test coverage
  contracts/hts-precompile/examples/token-create/TokenCreateContract.sol
  contracts/hts-precompile/examples/token-manage/TokenManagementContract.sol
  test/hts-precompile/assertions.js
  test/hts-precompile/token-create/tokenCreateContract.js
  test/hts-precompile/token-managment/tokenManagmentContract.js
Labels: enhancement, P1, Limechain

#121 ERC20 test coverage
  contracts/hts-precompile/examples/erc-20/ERC20Contract.sol
  test/hts-precompile/erc-20/ERC20Contract.js
Labels: enhancement, P2, Limechain

#124 ERC721 Test Coverage
  test/hts-precompile/erc-721/ERC721Contract.js
  test/hts-precompile/utils.js
Labels: enhancement, P2, Limechain
