Repository hashgraph/hedera-smart-contracts, pull requests merged in 2022-08, with the labels that each got.

#40 Add `Prng`Util Precompiles
  util-precompile/IPrngSystemContract.sol
  util-precompile/PrngSystemContract.sol
Labels: enhancement, P2

#49 Update HederaTokenService.sol with missing HIP 514 functions
  hts-precompile/HederaTokenService.sol
Labels: enhancement, P1

#41 Adds SafeHTS library
  safe-hts-precompile/HederaResponseCodes.sol
  safe-hts-precompile/SafeHTS.sol
  safe-hts-precompile/SafeOperations.sol
Labels: HTS, P2

#54 Update FeeHelper contract
  hts-precompile/FeeHelper.sol
Labels: enhancement, P2
