Repository hashgraph/hedera-smart-contracts, pull requests merged in 2023-12, with the labels that each got.

#604 Аdds oz beacon proxy tests
  artifacts/contracts/beacon-proxy/LogicContractV1.sol/LogicContractV1.dbg.json
  artifacts/contracts/beacon-proxy/LogicContractV1.sol/LogicContractV1.json
  artifacts/contracts/beacon-proxy/LogicContractV2.sol/LogicContractV2.dbg.json
  artifacts/contracts/beacon-proxy/LogicContractV2.sol/LogicContractV2.json
  artifacts/contracts/beacon-proxy/MyBeacon.sol/MyBeacon.dbg.json
  artifacts/contracts/beacon-proxy/MyBeacon.sol/MyBeacon.json
  artifacts/contracts/beacon-proxy/MyProxy.sol/MyProxy.dbg.json
  artifacts/contracts/beacon-proxy/MyProxy.sol/MyProxy.json
  contracts/solidity/oz/beacon-proxy/LogicContractV1.sol
  contracts/solidity/oz/beacon-proxy/LogicContractV2.sol
  contracts/solidity/oz/beacon-proxy/MyBeacon.sol
  contracts/solidity/oz/beacon-proxy/MyProxy.sol
  test/solidity/oz/beacon-proxy/beaconProxy.js
Labels: Limechain, EVM, Tooling

#611 feat: add PR title check workflow
  .github/workflows/flow-pr-title-check.yml
Labels: Limechain

#594 feat: [OZ] ERC-2771 Forwarder tests
  artifacts/contracts/solidity/oz/ERC-2771/ERC2771Context.sol/ERC2771ContextTest.json
  artifacts/contracts/solidity/oz/ERC-2771/ERC2771Forward.sol/ERC2771ForwardTest.json
  contracts/solidity/oz/ERC-2771/ERC2771Context.sol
  contracts/solidity/oz/ERC-2771/ERC2771Forward.sol
  test/solidity/oz/erc2771/context.js
  test/solidity/oz/erc2771/forward.js
  test/solidity/oz/helpers/eip712.js
Labels: Limechain, EVM, Tooling

#617 feat: Adding besu local node config
  TEST_SETUP.md
  hardhat.config.js
  utils/constants.js
Labels: enhancement, Limechain

#606 feat: [OZ] ERC-2612 - Permit
  artifacts/contracts/solidity/oz/ERC-2612/ERC2612.sol/ERC2612Test.json
  contracts/solidity/oz/ERC-2612/ERC2612.sol
  test/solidity/oz/ERC-2612/erc-2612.js
Labels: Limechain, EVM, Tooling

#609 feat: added OZ Access control example (#539)
  contracts/oz/access-control/AccessControlContract.sol
  test/OZ/access-control/accessControl.js
Labels: enhancement

#602 feat: added erc 4626 token standard example (#538)
  artifacts/contracts/proxy-upgrade/counter/Counter.sol/Counter.json
  artifacts/contracts/proxy-upgrade/counter/CounterV2.sol/CounterV2.json
  artifacts/contracts/proxy-upgrade/exchange/Exchange.sol/Exchange.json
  artifacts/contracts/proxy-upgrade/exchange/ExchangeV2.sol/ExchangeV2.json
  contracts/oz/erc-4626/TokenVault.sol
  contracts/solidity/inhetitance/Main.sol
  test/oz/erc-4626/TokenVault.js
Labels: enhancement

#615 feat: added example to showcase OZ ERC1967Upgrade (#613)
  artifacts/contracts/solidity/oz/ERC1967Upgrade/VoteProxy.sol/VoteProxy.json
  artifacts/contracts/solidity/oz/ERC1967Upgrade/VoteV1.sol/VoteV1.json
  artifacts/contracts/solidity/oz/ERC1967Upgrade/VoteV2.sol/VoteV2.json
  contracts/solidity/oz/ERC1967Upgrade/VoteProxy.sol
  contracts/solidity/oz/ERC1967Upgrade/VoteV1.sol
  contracts/solidity/oz/ERC1967Upgrade/VoteV2.sol
  test/solidity/oz/ERC1967Upgrade/Vote.js
Labels: enhancement, EVM, Tooling

#620 feat: added OZ ERC777 example (#546)
  artifacts/contracts/solidity/ERC777/ERC777ContractAccount.sol/ERC777ContractAccount.json
  artifacts/contracts/solidity/ERC777/ERC777Token.sol/ERC777Token.json
  artifacts/contracts/solidity/ERC777/hooks/ERC777RecipientHookImpl.sol/ERC777RecipientHookImpl.json
  artifacts/contracts/solidity/ERC777/hooks/ERC777SenderHookImpl.sol/ERC777SenderHookImpl.json
  artifacts/contracts/solidity/ERC777/introspection/ERC1820Registry.sol/ERC1820ImplementerInterface.json
  artifacts/contracts/solidity/ERC777/introspection/ERC1820Registry.sol/ERC1820Registry.json
  contracts/solidity/ERC777/ERC777ContractAccount.sol
  contracts/solidity/ERC777/ERC777Token.sol
  contracts/solidity/ERC777/hooks/ERC777RecipientHookImpl.sol
  contracts/solidity/ERC777/hooks/ERC777SenderHookImpl.sol
  contracts/solidity/ERC777/introspection/ERC1820Registry.sol
  package-lock.json
  test/solidity/oz/erc777/ERC777ContractAccount.js
  test/solidity/oz/erc777/ERC777Token.js
  test/solidity/oz/erc777/introspection/ERC1820Registry.js
Labels: enhancement, P2, EVM, Tooling

#627 feat(docs): added new README file under contracts/ folder (#621)
  contracts/README.md
Labels: enhancement

#628 feat: added examples to showcase the support for OZ IERC721Receiver (#625)
  artifacts/contracts/openzeppelin/ERC-721-Receiver/ERC721Receiver.sol/InvalidERC721Receiver.json
  artifacts/contracts/openzeppelin/ERC-721-Receiver/ERC721Receiver.sol/ValidERC721Receiver.json
  contracts/openzeppelin/ERC-721-Receiver/ERC721Receiver.sol
  test/constants.js
  test/openzeppelin/ERC-721-Receiver/ERC721Receiver.js
Labels: enhancement, EVM, Tooling

#631 docs: Bump 0.7.0-rc1
  package-lock.json
  package.json
Labels: enhancement

#632 docs: Bump 0.8.0-SNAPSHOT
  package-lock.json
  package.json
Labels: enhancement

#635 feat: added oz governor example (#540)
  artifacts/contracts/openzeppelin/governor/ExampleGovernor.sol/ExampleGovernor.json
  artifacts/contracts/openzeppelin/governor/ExampleTokenVote.sol/ExampleTokenVote.json
  contracts/openzeppelin/governor/ExampleGovernor.sol
  contracts/openzeppelin/governor/ExampleTokenVote.sol
  test/constants.js
  test/openzeppelin/governor/ExampleGovernor.js
  test/openzeppelin/governor/ExampleTokenVote.js
Labels: enhancement

#629 feat: Adding tests for Safe Remote Purchase contract
  artifacts/contracts/solidity/safe-remote-purchase/SafeRemotePurchase.sol/Purchase.json
  contracts/solidity/safe-remote-purchase/SafeRemotePurchase.sol
  test/constants.js
  test/solidity/safe-remote-purchase/safe-remote-purchase.js
Labels: enhancement, P1, Limechain, EVM
