Repository hashgraph/hedera-smart-contracts, pull requests merged in 2023-11, with the labels that each got.

#522 feat: added bitwise coverage solidity example contract (#519)
  contracts/yul/bitwise-coverage/Bitwise.sol
  test/yul/bitwise-coverage/Bitwise.js
Labels: enhancement, P2, EVM, Tooling

#525 feat: added DataAllocation solidity example contract
  contracts/yul/data-allocation/DataAllocation.sol
  test/yul/data-allocation/DataAllocation.js
Labels: enhancement, P2, EVM, Tooling

#528 feat: added TransactionInfo solidity example contract (#527)
  contracts/yul/transaction-information/TransactionInfo.sol
  test/yul/transaction-information/TransactionInfo.js
Labels: enhancement, P2, EVM, Tooling

#501 Adding tests for NonExistant account
  contracts/solidity/account/NonExisting.sol
  contracts/solidity/account/NonExtDup.sol
  test/constants.js
  test/solidity/account/nonExisting.js
Labels: enhancement, P1, Limechain, EVM

#559 Bump 0.6.0-rc1
  package.json
Labels: enhancement

#560 Bump 0.7.0-SNAPSHOT
  package.json
Labels: enhancement

#567 update: renamed methods in ControlStructures contract (#566)
  contracts/solidity/control/ControlStructures.sol
  test/solidity/control/control.js
Labels: enhancement, Tooling

#498 Adds tests for parameter restructuring and assignment
  contracts/solidity/assignments/AssignmentReferenceTypes.sol
  contracts/solidity/assignments/DestructuringReturns.sol
  test/constants.js
  test/solidity/assignments/assignments.js
Labels: enhancement, P1, EVM

#555 Adding tests for [OZ] ERC-2981
  contracts/solidity/errors/Errors.sol
  contracts/solidity/oz/ERC-2981/ERC2981.sol
  test/solidity/oz/erc2981/erc2981.js
Labels: P2, Limechain, EVM, Tooling

#508 487 Solidity Support Modifiers
  contracts/solidity/modifiers/A.sol
  contracts/solidity/modifiers/B.sol
  contracts/solidity/modifiers/DerivedContract.sol
  contracts/solidity/modifiers/Modifiers.sol
  test/solidity/modifiers/Modifiers.js
Labels: enhancement

#531 feat: added ContractCreator solidity example contract (#530)
  contracts/solidity/modular/Token.sol
  contracts/yul/contract-creator/ContractCreator.sol
  test/solidity/address/AssemblyAddress.js
  test/yul/contract-creator/ContractCreator.js
Labels: enhancement, P2, EVM

#570 feat: added VestingWallet solidity example contract (#554)
  contracts/OZ/finance/VestingWallet.sol
  test/OZ/finanace/VestingWallet.js
Labels: enhancement, EVM, Tooling

#535 feat: added ContractCaller solidity example contract (#534)
  contracts/yul/contract-caller/ContractCaller.sol
  contracts/yul/math-coverage/MatchCoverage.sol
  test/yul/contract-caller/ContractCaller.js
Labels: enhancement, P2, EVM

#543 Adding tests for [OZ] ERC-165
  contracts/oz/ERC-165/ClimberSelector.sol
  contracts/oz/ERC-165/IClimber.sol
  contracts/oz/ERC-165/Test_ERC165.sol
  test/constants.js
  test/solidity/oz/erc165/erc165.js
Labels: P2, Limechain, EVM

#548 Adding tests for [OZ] Multicall example
  contracts/oz/multicall/MulticallTest.sol
  test/constants.js
  test/solidity/oz/multicall/multicall.js
Labels: P2, Limechain, EVM

#502 Added tests around the voting ballot contract.
  TEST_SETUP.md
  contracts/solidity/voting/Ballot.sol
  hardhat.config.js
  local.env
  test/solidity/voting/Ballot.js
  utils/constants.js
Labels: enhancement

#524 EVM Precompiles support
  contracts/evm/Precompiles.sol
  package-lock.json
  package.json
  test/evm/Precompiles.js
Labels: enhancement

#500 Block information tests.
  contracts/solidity/block/BlockInfo.sol
  test/constants.js
  test/solidity/block/BlockInfo.js
Labels: enhancement

#551 Adding tests for [OZ] ERC-20 Votes contract
  artifacts/contracts/proxy-upgrade/counter/Counter.sol/Counter.json
  artifacts/contracts/proxy-upgrade/counter/CounterV2.sol/CounterV2.json
  artifacts/contracts/proxy-upgrade/exchange/Exchange.sol/Exchange.json
  artifacts/contracts/proxy-upgrade/exchange/ExchangeV2.sol/ExchangeV2.json
  contracts/solidity/oz/ERC-165/ClimberSelector.sol
  contracts/solidity/oz/ERC-165/IClimber.sol
  contracts/solidity/oz/ERC-165/Test_ERC165.sol
  contracts/solidity/oz/ERC-20-votes/erc20VotesTest.sol
  contracts/solidity/oz/finance/VestingWallet.sol
  contracts/solidity/oz/multicall/MulticallTest.sol
  test/constants.js
  test/solidity/oz/erc20votes/erc20Votes.js
Labels: P2, Limechain, EVM, Tooling

#562 Adding tests for [OZ] ERC-2771 Context
  contracts/solidity/oz/ERC-2771/ERC2771Context.sol
  test/solidity/oz/erc-2771/context.js
Labels: P2, Limechain, EVM, Tooling

#586 571 polling required ci runner
  .github/workflows/dapp-playground-workflow.yml
  .github/workflows/foundry_test.yml
  .github/workflows/release-production.yml
  .github/workflows/test-workflow.yml
  local.env
Labels: bug, enhancement

#533 Solidity Coverage - Signature example
  contracts/solidity/signature-example/ReceiverPays.sol
  test/constants.js
  test/solidity/signature-example/ReceiverPays.js
  test/solidity/typeops/TypeOps.js
Labels: enhancement

#579 update: renamed methods in Panic contract to fix foundry-test in CI (#578)
  contracts/solidity/errors/Panic.sol
  test/solidity/errors/panicErrors.js
Labels: enhancement, EVM, Tooling

#573 feat: added ContractCreatorOZCreate2 solidity example contract (#568)
  contracts/OZ/create2/ContractCreatorOZCreate2.sol
  test/OZ/create2/ContractCreatorOZCreate2.js
Labels: enhancement, EVM, Tooling

#591 feat: add OZ contract manual GitHub action to run OZ examples (#577)
  .github/workflows/solidity-tests.yml
  contracts/solidity/oz/create2/ContractCreatorOZCreate2.sol
  test/proxy-upgrade/proxyUpgradeContracts.js
  test/solidity/oz/create2/ContractCreatorOZCreate2.js
  test/solidity/oz/erc-2771/context.js
  test/solidity/oz/erc165/erc165.js
  test/solidity/oz/erc20votes/erc20Votes.js
  test/solidity/oz/erc2981/erc2981.js
  test/solidity/oz/finanace/VestingWallet.js
  test/solidity/oz/multicall/multicall.js
  test/solidity/oz/pausable/pausable.js
Labels: P2, EVM, Tooling

#532 Adding tests for the Simple Auction smart contract.
  artifacts/contracts/solidity/simple-auction/SimpleAuction.sol/SimpleAuction.dbg.json
  artifacts/contracts/solidity/simple-auction/SimpleAuction.sol/SimpleAuction.json
  contracts/solidity/simple-auction/SimpleAuction.sol
  hardhat.config.js
  test/constants.js
  test/solidity/errors/errors.js
  test/solidity/simple-auction/simple-auction.js
  utils/helpers.js
Labels: enhancement, P2, Limechain, EVM

#575 487 modifiers
  test/solidity/modifiers/Modifiers.js
Labels: enhancement
