Repository hashgraph/hedera-smart-contracts, pull requests merged in 2023-04, with the labels that each got.

#202 Redirect for token test failure
  artifacts/contracts/erc-721/ERC721Mock.sol/ERC721Mock.json
  artifacts/contracts/hip-583/ERC721Mock.sol/ERC721Mock.json
  test/hts-precompile/redirect-for-token.js
Labels: enhancement

#213 Add tests for the ERC20 extensions
  artifacts/contracts/erc-20-extensions/ERC20Extensions.sol/ERC20BurnableMock.json
  artifacts/contracts/erc-20-extensions/ERC20Extensions.sol/ERC20CappedMock.json
  artifacts/contracts/erc-20-extensions/ERC20Extensions.sol/ERC20PausableMock.json
  artifacts/contracts/erc-20-extensions/ERC20Extensions.sol/ERC20SnapshotMock.json
  contracts/erc-20-extensions/ERC20Extensions.sol
  test/erc-20-extensions/ERC20Extensions.js
Labels: enhancement

#217 Adding missing license headers
  test/diamond-pattern/diamond.js
  test/erc-1155/ERC1155.js
  test/erc-20/ERC20.js
  test/erc-721/ERC721.js
  test/hip-583/HIP583.js
  test/hts-precompile/assertions.js
  test/hts-precompile/erc-20/ERC20Contract.js
  test/hts-precompile/erc-721/ERC721Contract.js
  test/hts-precompile/redirect-for-token.js
  test/hts-precompile/token-create/tokenCreateContract.js
  test/hts-precompile/token-managment/tokenManagmentContract.js
  test/hts-precompile/token-query/tokenQueryContract.js
  test/hts-precompile/token-transfer/tokenTransferContract.js
  test/hts-precompile/utils.js
  test/proxy-upgrade/proxyUpgradeContracts.js
  test/safe-hts-precompile/SafeHTS.js
Labels: enhancement, good first issue, P3

#209 Refactor constants
  test/constants.js
  test/diamond-pattern/diamond.helper.js
  test/diamond-pattern/diamond.js
  test/erc-1155/ERC1155.js
  test/erc-20/ERC20.js
  test/erc-721/ERC721.js
  test/hip-583/HIP583.js
  test/hts-precompile/erc-20/ERC20Contract.js
  test/hts-precompile/erc-721/ERC721Contract.js
  test/hts-precompile/redirect-for-token.js
  test/hts-precompile/token-create/tokenCreateContract.js
  test/hts-precompile/token-managment/tokenManagmentContract.js
  test/hts-precompile/token-query/tokenQueryContract.js
  test/hts-precompile/token-transfer/tokenTransferContract.js
  test/hts-precompile/utils.js
  test/proxy-upgrade/proxyUpgradeContracts.js
  test/safe-hts-precompile/SafeHTS.js
Labels: enhancement, good first issue, P3, Limechain

#222 Remove constants from erc20 extension tests
  test/constants.js
  test/erc-20-extensions/ERC20Extensions.js
Labels: enhancement, P3, Limechain

#225 Add test reporting to pipelines
  .github/workflows/test-workflow.yml
  .github/workflows/tests.yml
  hardhat.config.js
  package-lock.json
  package.json
Labels: enhancement

#226 Add CODEOWNERS
  .github/CODEOWNERS
Labels: enhancement
