Repository hashgraph/hedera-smart-contracts, pull requests merged in 2023-08, with the labels that each got.

#269 System contract dapp playground
  system-contract-dapp-playground/.eslintrc.json
  system-contract-dapp-playground/.gitignore
  system-contract-dapp-playground/.prettierrc
  system-contract-dapp-playground/Makefile
  system-contract-dapp-playground/README.md
  system-contract-dapp-playground/next.config.js
  system-contract-dapp-playground/package-lock.json
  system-contract-dapp-playground/package.json
  system-contract-dapp-playground/postcss.config.js
  system-contract-dapp-playground/public/brandings/hedera-logo.png
  system-contract-dapp-playground/public/hederafavicon.ico
  system-contract-dapp-playground/src/app/layout.tsx
  system-contract-dapp-playground/src/app/page.tsx
  system-contract-dapp-playground/src/fonts/index.ts
  system-contract-dapp-playground/src/fonts/styreneA-webfont/1802-UFGULA.css
  system-contract-dapp-playground/src/fonts/styreneA-webfont/1802-UFGULA.html
  system-contract-dapp-playground/src/fonts/styreneA-webfont/StyreneA-Black-Web.woff2
  system-contract-dapp-playground/src/fonts/styreneA-webfont/StyreneA-BlackItalic-Web.woff2
  system-contract-dapp-playground/src/fonts/styreneA-webfont/StyreneA-Bold-Web.woff2
  system-contract-dapp-playground/src/fonts/styreneA-webfont/StyreneA-BoldItalic-Web.woff2
  system-contract-dapp-playground/src/fonts/styreneA-webfont/StyreneA-Light-Web.woff2
  system-contract-dapp-playground/src/fonts/styreneA-webfont/StyreneA-LightItalic-Web.woff2
  system-contract-dapp-playground/src/fonts/styreneA-webfont/StyreneA-Medium-Web.woff2
  system-contract-dapp-playground/src/fonts/styreneA-webfont/StyreneA-MediumItalic-Web.woff2
  system-contract-dapp-playground/src/fonts/styreneA-webfont/StyreneA-Regular-Web.woff2
  system-contract-dapp-playground/src/fonts/styreneA-webfont/StyreneA-RegularItalic-Web.woff2
  system-contract-dapp-playground/src/fonts/styreneA-webfont/StyreneA-Thin-Web.woff2
  system-contract-dapp-playground/src/fonts/styreneA-webfont/StyreneA-ThinItalic-Web.woff2
  system-contract-dapp-playground/src/fonts/styreneA-webfont/_How_To_Install_Webfonts.html
  system-contract-dapp-playground/src/libs/chakra/provider.tsx
  system-contract-dapp-playground/src/styles/globals.css
  system-contract-dapp-playground/src/utils/metadata.ts
  system-contract-dapp-playground/tailwind.config.js
  system-contract-dapp-playground/tsconfig.json
Labels: documentation, enhancement, P2

#273 feat: added connect wallet feature to Dapp
  system-contract-dapp-playground/package-lock.json
  system-contract-dapp-playground/package.json
  system-contract-dapp-playground/src/api/cookies/index.ts
  system-contract-dapp-playground/src/api/wallet/index.ts
  system-contract-dapp-playground/src/app/(protected)/overview/page.tsx
  system-contract-dapp-playground/src/components/toast/CommonToast.tsx
  system-contract-dapp-playground/src/middleware.ts
  system-contract-dapp-playground/src/sections/landing/index.tsx
  system-contract-dapp-playground/src/types/interfaces.d.ts
  system-contract-dapp-playground/src/utils/constants.ts
  system-contract-dapp-playground/tailwind.config.js
Labels: enhancement, P1

#294 fix: unblocked compile command from requiring env variables be set (#293)
  utils/constants.js
Labels: bug, P2

#292 feat: added validation check for contract metadata (#280)
  system-contract-dapp-playground/README.md
  system-contract-dapp-playground/contracts-info/index.ts
  system-contract-dapp-playground/package-lock.json
  system-contract-dapp-playground/package.json
  system-contract-dapp-playground/scripts/prerequisite-check.ts
  system-contract-dapp-playground/src/sections/landing/index.tsx
Labels: enhancement, P2, Tooling

#297 feat: added new logged in Navbar and WalletPopup UI components (#295)
  system-contract-dapp-playground/__tests__/mirror-node/index.test.ts
  system-contract-dapp-playground/jest.config.mjs
  system-contract-dapp-playground/package-lock.json
  system-contract-dapp-playground/package.json
  system-contract-dapp-playground/public/assets/icons/disconnect-icon.png
  system-contract-dapp-playground/public/assets/icons/hashscan-icon.png
  system-contract-dapp-playground/public/assets/icons/list-icon.png
  system-contract-dapp-playground/src/api/cookies/index.ts
  system-contract-dapp-playground/src/api/mirror-node/index.ts
  system-contract-dapp-playground/src/api/wallet/index.ts
  system-contract-dapp-playground/src/app/layout.tsx
  system-contract-dapp-playground/src/app/page.tsx
  system-contract-dapp-playground/src/components/footer/index.tsx
  system-contract-dapp-playground/src/components/navbar/index.tsx
  system-contract-dapp-playground/src/components/wallet-popup/index.tsx
  system-contract-dapp-playground/src/middleware.ts
  system-contract-dapp-playground/src/sections/landing/index.tsx
  system-contract-dapp-playground/src/types/interfaces.d.ts
  system-contract-dapp-playground/src/utils/constants.ts
  system-contract-dapp-playground/src/utils/helpers.ts
  system-contract-dapp-playground/tailwind.config.js
  system-contract-dapp-playground/tsconfig.json
Labels: enhancement, P2, Tooling

#299 Add return statement to `HederaTokenService.redirectForToken()`
  artifacts/contracts/hts-precompile/HederaTokenService.sol/HederaTokenService.json
  artifacts/contracts/hts-precompile/IHederaTokenService.sol/IHederaTokenService.json
  artifacts/contracts/hts-precompile/KeyHelper.sol/Bits.json
  artifacts/contracts/hts-precompile/examples/token-create/TokenCreateContract.sol/TokenCreateContract.json
  artifacts/contracts/hts-precompile/examples/token-create/TokenCreateCustom.sol/TokenCreateCustomContract.json
  artifacts/contracts/hts-precompile/examples/token-manage/TokenManagementContract.sol/TokenManagementContract.json
  artifacts/contracts/hts-precompile/examples/token-query/TokenQueryContract.sol/TokenQueryContract.json
  artifacts/contracts/hts-precompile/examples/token-transfer/TokenTransferContract.sol/TokenTransferContract.json
  artifacts/contracts/proxy-upgrade/exchange/Exchange.sol/Exchange.json
  artifacts/contracts/proxy-upgrade/exchange/ExchangeV2.sol/ExchangeV2.json
  artifacts/contracts/safe-hts-precompile/SafeOperations.sol/SafeOperations.json
  artifacts/contracts/safe-hts-precompile/SafeViewOperations.sol/SafeViewOperations.json
  contracts/hts-precompile/HederaTokenService.sol
  contracts/hts-precompile/IHederaTokenService.sol
Labels: enhancement, Limechain

#305 feat: added new UI component for HTS-206 route & reworked smart contract assets (#302)
  system-contract-dapp-playground/contracts-info/index.ts
  system-contract-dapp-playground/src/api/wallet/index.ts
  system-contract-dapp-playground/src/app/hedera/hts-hip-206/page.tsx
  system-contract-dapp-playground/src/components/footer/index.tsx
  system-contract-dapp-playground/src/components/navbar/index.tsx
  system-contract-dapp-playground/src/components/wallet-popup/index.tsx
  system-contract-dapp-playground/src/sections/hts-hip-206/index.tsx
  system-contract-dapp-playground/src/sections/landing/index.tsx
  system-contract-dapp-playground/src/styles/globals.css
  system-contract-dapp-playground/src/types/interfaces.d.ts
  system-contract-dapp-playground/src/utils/constants.ts
  system-contract-dapp-playground/tailwind.config.js
  system-contract-dapp-playground/tsconfig.json
Labels: enhancement, P2, Tooling

#306 feat: Added new deploySmartContract() API, reworked getHederaNativeIDFromEVMaddress API logic, reworked HEDERA_SMART_CONTRACTS_ASSETS constant logic(#303)
  system-contract-dapp-playground/__tests__/hedera/index.test.ts
  system-contract-dapp-playground/__tests__/mirror-node/index.test.ts
  system-contract-dapp-playground/src/api/hedera/index.ts
  system-contract-dapp-playground/src/api/mirror-node/index.ts
  system-contract-dapp-playground/src/components/wallet-popup/index.tsx
  system-contract-dapp-playground/src/sections/hts-hip-206/index.tsx
  system-contract-dapp-playground/src/types/interfaces.d.ts
  system-contract-dapp-playground/src/utils/constants.ts
Labels: enhancement, P2, Tooling

#308 feat: added new contractInteraction UI component && deploy support and deployed contract details for HTS example contracts (#304, #282, #286, #287, #288)
  system-contract-dapp-playground/src/api/cookies/index.ts
  system-contract-dapp-playground/src/components/common/AlertDialog.tsx
  system-contract-dapp-playground/src/components/contract-interaction/index.tsx
  system-contract-dapp-playground/src/sections/hts-hip-206/index.tsx
  system-contract-dapp-playground/src/utils/helpers.ts
Labels: enhancement, P2, Tooling

#309 feat: Added deployment support and deployed contract details for HRCcontract.sol (#283)
  system-contract-dapp-playground/src/app/hedera/hrc-719/page.tsx
  system-contract-dapp-playground/src/sections/hrc-719/index.tsx
  system-contract-dapp-playground/src/sections/hts-hip-206/index.tsx
  system-contract-dapp-playground/src/types/interfaces.d.ts
  system-contract-dapp-playground/src/utils/constants.ts
Labels: enhancement, P2, Tooling

#310 feat: Added deployment support and deployed contract details for exchangeRatePrecompile.sol (#289)
  system-contract-dapp-playground/src/app/hedera/exchange-rate-hip-475/page.tsx
  system-contract-dapp-playground/src/components/common/AlertDialog.tsx
  system-contract-dapp-playground/src/components/common/HederaCommonTextField.tsx
  system-contract-dapp-playground/src/components/contract-interaction/index.tsx
  system-contract-dapp-playground/src/components/exchange-rate-hip-475/ExchangeRateDeployField.tsx
  system-contract-dapp-playground/src/sections/exchange-rate-hip-475/index.tsx
  system-contract-dapp-playground/src/types/interfaces.d.ts
  system-contract-dapp-playground/src/utils/constants.ts
  system-contract-dapp-playground/src/utils/helpers.ts
Labels: enhancement, P2, Tooling

#311 feat: Added deployment support and deployed contract details for prngSystemContract.sol (#290)
  system-contract-dapp-playground/src/app/hedera/prng-hip-351/page.tsx
  system-contract-dapp-playground/src/components/contract-interaction/index.tsx
  system-contract-dapp-playground/src/sections/prng-hip-351/index.tsx
Labels: enhancement, P1

#327 feat: Added new UI component for ERC20Mock contract interactions (#325)
  system-contract-dapp-playground/src/api/ethers/index.ts
  system-contract-dapp-playground/src/components/contract-interaction/erc/deployment/ERCDeployField.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/common/MultiLineMethod.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/common/OneLineMethod.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/BalanceOf.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/Mint.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/TokenInformation.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/TokenPermissions.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/Transfer.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/utils/constant.ts
  system-contract-dapp-playground/src/components/contract-interaction/exchange-rate-hip-475/deployment/ExchangeRateDeployField.tsx
  system-contract-dapp-playground/src/components/contract-interaction/index.tsx
  system-contract-dapp-playground/src/types/interfaces.d.ts
  system-contract-dapp-playground/src/utils/constants.ts
  system-contract-dapp-playground/src/utils/helpers.ts
Labels: enhancement, P2, Tooling

#328 feat: added necessary solidity methods and its unit tests for tokenCreateCustom.sol (#315)
  artifacts/contracts/hts-precompile/examples/token-create/TokenCreateCustom.sol/TokenCreateCustomContract.json
  contracts/hts-precompile/examples/token-create/TokenCreateCustom.sol
  test/constants.js
  test/hts-precompile/token-create/tokenCreateCustomContract.js
  test/hts-precompile/utils.js
Labels: enhancement, P2, Tooling

#334 update: Added necessary interface for ERC20Mock contract (#332) & reworked logic for OneLineMethod and MultiLineMethod component (#333)
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/common/MultiLineMethod.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/common/OneLineMethod.tsx
  system-contract-dapp-playground/src/types/interfaces.d.ts
Labels: enhancement, P2, Tooling

#331 fixed: fixed contract types for contract interaction logic (#330)
  system-contract-dapp-playground/__tests__/ethers/index.test.ts
  system-contract-dapp-playground/src/api/ethers/index.ts
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/BalanceOf.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/Mint.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/TokenInformation.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/TokenPermissions.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/Transfer.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/index.tsx
  system-contract-dapp-playground/src/types/interfaces.d.ts
Labels: enhancement, P2, Tooling

#344 update: replaced tokenCreateCustomContract with tokenCreateContract in `Hapi vs Ethereum` test suite
  test/hts-precompile/token-create/tokenCreateContract.js
Labels: enhancement

#343 test: added unit tests to fix #342
  test/hts-precompile/token-create/tokenCreateCustomContract.js
Labels: enhancement, P2, Tooling

#345 dapp-feat: added APIs, unit tests for tokenInformation and integrated new logic to TokenInformation UI component (#335)
  system-contract-dapp-playground/__tests__/hedera/erc20-interactions/index.test.ts
  system-contract-dapp-playground/src/api/hedera/erc20-interactions/index.ts
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/TokenInformation.tsx
Labels: enhancement, P2, Tooling

#348 feat: added APIs & unit tests to support minting tokens and querying token balance (#336 #337)
  system-contract-dapp-playground/__tests__/hedera/erc20-interactions/index.test.ts
  system-contract-dapp-playground/src/api/hedera/erc20-interactions/index.ts
  system-contract-dapp-playground/src/api/localStorage/index.ts
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/BalanceOf.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/Mint.tsx
Labels: enhancement, P2, Tooling

#347 update: Update TokenCreateCustomContract to dynamically accept an off-chain keys array (#346)
  artifacts/contracts/hts-precompile/examples/token-create/TokenCreateCustom.sol/TokenCreateCustomContract.json
  contracts/hts-precompile/examples/token-create/TokenCreateCustom.sol
  test/hts-precompile/token-create/tokenCreateCustomContract.js
  test/hts-precompile/utils.js
Labels: enhancement, P2, Tooling

#349 feat: added APIs, unit tests for token permissions and integrated new logic to TokenPermissions UI component (#338)
  system-contract-dapp-playground/__tests__/hedera/erc20-interactions/index.test.ts
  system-contract-dapp-playground/src/api/hedera/erc20-interactions/index.ts
  system-contract-dapp-playground/src/api/localStorage/index.ts
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/TokenPermissions.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/utils/constant.ts
Labels: enhancement, P2, Tooling

#351 dapp-feat: added APIs, unit tests for token transfer and integrated new logic to Transfer UI component (#339)
  system-contract-dapp-playground/__tests__/hedera/erc20-interactions/index.test.ts
  system-contract-dapp-playground/src/api/hedera/erc20-interactions/index.ts
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/Transfer.tsx
Labels: enhancement, P2, Tooling

#354 feat: Added API and unit tests to facilitate fungible and non-fungible token creations for TokenCreateCustom contract
  system-contract-dapp-playground/__tests__/hedera/helper/index.test.ts
  system-contract-dapp-playground/__tests__/hedera/hts-interactions/index.test.ts
  system-contract-dapp-playground/src/api/hedera/tokenCreateCustom-interactions/index.ts
  system-contract-dapp-playground/src/types/contract-interactions/HTS/index.d.ts
  system-contract-dapp-playground/src/utils/contract-interactions/HTS/constant.ts
  system-contract-dapp-playground/src/utils/contract-interactions/HTS/helpers.ts
Labels: enhancement, P2, Tooling

#355 feat: Added API and unit tests to facilitate token mint, token associating, and granting kyc for TokenCreateCustom contract
  system-contract-dapp-playground/__tests__/hedera/hts-interactions/index.test.ts
  system-contract-dapp-playground/src/api/hedera/tokenCreateCustom-interactions/index.ts
  system-contract-dapp-playground/src/types/contract-interactions/HTS/index.d.ts
Labels: enhancement, P2, Tooling

#356 feat: set up UI components and methods for integrating the tokenCreateCustom contract's methods into the DApp
  system-contract-dapp-playground/__tests__/hedera/helper/index.test.ts
  system-contract-dapp-playground/__tests__/hedera/hts-interactions/index.test.ts
  system-contract-dapp-playground/src/api/hedera/tokenCreateCustom-interactions/index.ts
  system-contract-dapp-playground/src/api/localStorage/index.ts
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/TokenPermissions.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/shared/sharedComponents.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/shared/sharedMethods.tsx
  system-contract-dapp-playground/src/components/contract-interaction/index.tsx
  system-contract-dapp-playground/src/types/contract-interactions/HTS/index.d.ts
  system-contract-dapp-playground/src/utils/common/constants.ts
  system-contract-dapp-playground/src/utils/common/helpers.ts
  system-contract-dapp-playground/src/utils/contract-interactions/HTS/constant.ts
  system-contract-dapp-playground/src/utils/contract-interactions/HTS/helpers.ts
Labels: enhancement, P2, Tooling

#357 feat: incorporated a UI component for the FungibleTokenCreate method within the TokenCreateCustom contract.
  system-contract-dapp-playground/__tests__/hedera/helper/index.test.ts
  system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/ParamInputForm.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/SigningKeysForm.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/TransactionResultTable.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/shared/methods/handleAPIErrors.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/shared/methods/handleSanitizeFormInputs.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/shared/methods/signingKeys.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/FungibleTokenCreate.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/shared/sharedMethods.tsx
  system-contract-dapp-playground/src/utils/contract-interactions/HTS/helpers.ts
  system-contract-dapp-playground/src/utils/contract-interactions/HTS/token-create-custom/constant.ts
Labels: enhancement, P2, Tooling

#358 feat: incorporated UI component for the NonFungibleTokenCreate method…
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/NonFungibleTokenCreate.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/index.tsx
Labels: enhancement, P2, Tooling

#359 feat: incorporated UI component for the MintHederaToken method
  system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/MetadataInputForm.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/shared/hooks/usePaginatedTxResults.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/shared/hooks/useToastSuccessful.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/shared/hooks/useUpdateLocalStorage.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/shared/methods/handleRetrievingTransactionResultsFromLocalStorage.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/shared/states/commonStates.ts
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/FungibleTokenCreate.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/MintHederaToken.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/NonFungibleTokenCreate.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/index.tsx
Labels: enhancement, P2, Tooling

#360 feat: incorporated UI component for the TokenAssociation & GrantTokenKYC method
  system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/MetadataInputForm.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/ParamInputForm.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/TokenAddressesInputForm.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/shared/hooks/useToastSuccessful.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/shared/hooks/useUpdateLocalStorage.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/shared/methods/handleSanitizeFormInputs.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/AssociateHederaToken.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/GrantTokenKYC.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/index.tsx
  system-contract-dapp-playground/src/utils/contract-interactions/HTS/token-create-custom/constant.ts
Labels: enhancement, P2, Tooling
