Repository hashgraph/hedera-smart-contracts, pull requests merged in 2023-07, with the labels that each got.

#240 Add Shanghai test support #232
  .github/workflows/tests.yml
  artifacts/contracts/diamond-pattern/Diamond.sol/Diamond.json
  artifacts/contracts/diamond-pattern/DiamondInit.sol/DiamondInit.json
  artifacts/contracts/diamond-pattern/facets/DiamondCutFacet.sol/DiamondCutFacet.json
  artifacts/contracts/diamond-pattern/facets/DiamondLoupeFacet.sol/DiamondLoupeFacet.json
  artifacts/contracts/diamond-pattern/facets/OwnershipFacet.sol/OwnershipFacet.json
  artifacts/contracts/diamond-pattern/facets/Test1Facet.sol/Test1Facet.json
  artifacts/contracts/diamond-pattern/facets/Test2Facet.sol/Test2Facet.json
  artifacts/contracts/diamond-pattern/libraries/LibDiamond.sol/LibDiamond.json
  artifacts/contracts/erc-1155/ERC1155Mock.sol/ERC1155Mock.json
  artifacts/contracts/erc-20-extensions/ERC20Extensions.sol/ERC20BurnableMock.json
  artifacts/contracts/erc-20-extensions/ERC20Extensions.sol/ERC20CappedMock.json
  artifacts/contracts/erc-20-extensions/ERC20Extensions.sol/ERC20PausableMock.json
  artifacts/contracts/erc-20-extensions/ERC20Extensions.sol/ERC20SnapshotMock.json
  artifacts/contracts/erc-20/ERC20Mock.sol/ERC20Mock.json
  artifacts/contracts/erc-721/ERC721Mock.sol/ERC721Mock.json
  artifacts/contracts/exchange-rate-precompile/ExchangeRatePrecompile.sol/ExchangeRatePrecompile.json
  artifacts/contracts/hip-583/ContractTransferTx.sol/ContractTransferTx.json
  artifacts/contracts/hip-583/ERC20Mock.sol/ERC20Mock.json
  artifacts/contracts/hip-583/ERC721Mock.sol/ERC721Mock.json
  artifacts/contracts/hts-precompile/HederaResponseCodes.sol/HederaResponseCodes.json
  artifacts/contracts/hts-precompile/KeyHelper.sol/Bits.json
  artifacts/contracts/hts-precompile/examples/erc-20/ERC20Contract.sol/ERC20Contract.json
  artifacts/contracts/hts-precompile/examples/erc-721/ERC721Contract.sol/ERC721Contract.json
  artifacts/contracts/hts-precompile/examples/token-create/TokenCreateCustom.sol/TokenCreateCustomContract.json
  artifacts/contracts/hts-precompile/examples/token-manage/TokenManagementContract.sol/TokenManagementContract.json
  artifacts/contracts/hts-precompile/examples/token-query/TokenQueryContract.sol/TokenQueryContract.json
  artifacts/contracts/hts-precompile/examples/token-transfer/TokenTransferContract.sol/TokenTransferContract.json
  artifacts/contracts/multicaller/Multicall3.sol/Multicall3.json
  artifacts/contracts/multicaller/Receiver.sol/Receiver.json
  artifacts/contracts/multicaller/Reverter.sol/Reverter.json
  artifacts/contracts/native-precompiles/EcrecoverCaller.sol/EcrecoverCaller.json
  artifacts/contracts/proxy-upgrade/counter/Counter.sol/Counter.json
  artifacts/contracts/proxy-upgrade/counter/CounterV2.sol/CounterV2.json
  artifacts/contracts/proxy-upgrade/exchange/Exchange.sol/Exchange.json
  artifacts/contracts/proxy-upgrade/exchange/ExchangeV2.sol/ExchangeV2.json
  artifacts/contracts/safe-hts-precompile/HederaResponseCodes.sol/HederaResponseCodes.json
  artifacts/contracts/safe-hts-precompile/SafeHTS.sol/SafeHTS.json
  artifacts/contracts/safe-hts-precompile/SafeOperations.sol/SafeOperations.json
  artifacts/contracts/shanghai-opcodes/ShanghaiOpcodes.sol/ShanghaiOpcodes.json
  artifacts/contracts/util-precompile/PrngSystemContract.sol/PrngSystemContract.json
  contracts/multicaller/Multicall3.sol
  contracts/shanghai-opcodes/ShanghaiOpcodes.sol
  hardhat.config.js
  test/shanghai-opcodes/ShanghaiOpcodes.js
Labels: enhancement, P1

#219 Add new SafeHTS tests
  artifacts/contracts/hts-precompile/examples/hrc/HRCContract.sol/HRCContract.json
  artifacts/contracts/hts-precompile/examples/token-create/TokenCreateContract.sol/TokenCreateContract.json
  artifacts/contracts/safe-hts-precompile/SafeHTS.sol/SafeHTS.json
  artifacts/contracts/safe-hts-precompile/SafeOperations.sol/SafeOperations.json
  artifacts/contracts/safe-hts-precompile/SafeViewHTS.sol/SafeViewHTS.json
  artifacts/contracts/safe-hts-precompile/SafeViewOperations.sol/SafeViewOperations.json
  contracts/safe-hts-precompile/SafeHTS.sol
  contracts/safe-hts-precompile/SafeOperations.sol
  contracts/safe-hts-precompile/SafeViewHTS.sol
  contracts/safe-hts-precompile/SafeViewOperations.sol
  test/constants.js
  test/hts-precompile/utils.js
  test/safe-hts-precompile/SafeHTS.js
Labels: enhancement, HTS, Limechain

#267 Added development guidelines and clean up code (#262)
  .github/workflows/release-production.yml
  .github/workflows/test-workflow.yml
  .github/workflows/tests.yml
  .gitignore
  .prettierrc
  Makefile
  README.md
  TEST_SETUP.md
  contracts/exchange-rate-precompile/README.md
  contracts/hts-precompile/README.md
  contracts/util-precompile/README.md
  example.env
  hardhat.config.js
  local.env
  package-lock.json
  package.json
  test/README.md
  test/constants.js
  test/diamond-pattern/diamond.helper.js
  test/diamond-pattern/diamond.js
  test/erc-1155/ERC1155.js
  test/erc-20-extensions/ERC20Extensions.js
  test/erc-20/ERC20.js
  test/erc-721/ERC721.js
  test/hip-583/HIP583.js
  test/hts-precompile/assertions.js
  test/hts-precompile/erc-20/ERC20Contract.js
  test/hts-precompile/erc-20/IERC20.js
  test/hts-precompile/erc-721/ERC721Contract.js
  test/hts-precompile/hrc/HRCContract.js
  test/hts-precompile/redirect-for-token.js
  test/hts-precompile/token-create/tokenCreateContract.js
  test/hts-precompile/token-managment/tokenManagmentContract.js
  test/hts-precompile/token-query/tokenQueryContract.js
  test/hts-precompile/token-transfer/tokenTransferContract.js
  test/hts-precompile/utils.js
  test/multicall/Multicall.js
  test/native-precompiles/EcrecoverCaller.js
  test/proxy-upgrade/proxyUpgradeContracts.js
  test/safe-hts-precompile/SafeHTS.js
  test/shanghai-opcodes/ShanghaiOpcodes.js
  utils/constants.js
Labels: documentation, enhancement, P3
