Repository hashgraph/hedera-smart-contracts, pull requests merged in 2023-10, with the labels that each got.

#424 dapp-feat: Export Transaction to CSV feature complete (#421)
  system-contract-dapp-playground/package-lock.json
  system-contract-dapp-playground/package.json
  system-contract-dapp-playground/src/sections/activity/index.tsx
  system-contract-dapp-playground/src/types/contract-interactions/shared/index.d.ts
  system-contract-dapp-playground/src/utils/common/helpers.ts
Labels: enhancement, P2, Tooling

#433 dapp-feat: added query response data to READONLY transactions in main activity page (#427)
  system-contract-dapp-playground/src/components/activity/ActivityTransactionTable/index.tsx
  system-contract-dapp-playground/src/components/activity/ExtraOptionsButton/index.tsx
  system-contract-dapp-playground/src/components/activity/QueryResponseModal/index.tsx
  system-contract-dapp-playground/src/components/common/components/PageinationButtons.tsx
  system-contract-dapp-playground/src/components/common/components/TransactionResultTable.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/balance-of/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/mint/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/token-information/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/token-permission/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/token-transfer/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-721/methods/approve/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-721/methods/balance-of/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-721/methods/mint/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-721/methods/operator-approve/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-721/methods/token-information/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-721/methods/token-transfer/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/erc/erc-721/methods/token-uri/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/exchange-rate/methods/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/AssociateHederaToken/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/FungibleTokenCreate/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/GrantTokenKYC/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/MintHederaToken/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/NonFungibleTokenCreate/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/manageTokenDelete/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/manageTokenInfo/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/manageTokenPermission/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/manageTokenRelation/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/manageTokenStatus/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/manageTokenSupplyReduction/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-query-contract/methods/querySpecificToken/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-query-contract/methods/queryTokenGeneralInfo/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-query-contract/methods/queryTokenPermission/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-query-contract/methods/queryTokenStatus/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-query-contract/methods/queryTokenValidity/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-transfer-contract/method/transferCrypto/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-transfer-contract/method/transferMultipleTokens/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/hts/token-transfer-contract/method/transferSingleToken/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/ihrc/methods/index.tsx
  system-contract-dapp-playground/src/components/contract-interaction/prng/methods/index.tsx
  system-contract-dapp-playground/src/sections/activity/index.tsx
  system-contract-dapp-playground/src/utils/common/constants.ts
  system-contract-dapp-playground/src/utils/common/helpers.ts
Labels: enhancement, P2, Tooling

#439 dapp-docs: added source code documentation (#438)
  TEST_SETUP.md
  system-contract-dapp-playground/README.md
  system-contract-dapp-playground/docs/source-code-document/README.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/1.folder-tree/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/__tests__/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/config-files/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/prerequisite-check/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/public/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/src/api/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/src/app/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/src/components/activity/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/src/components/background-gradients/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/src/components/common/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/src/components/contract-interactions/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/src/components/footer/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/src/components/navbar/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/src/components/sidebar/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/src/components/toast/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/src/components/wallet-popup/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/src/fonts/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/src/hooks/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/src/libs/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/src/middleware.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/src/sections/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/src/styles/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/src/types/index.md
  system-contract-dapp-playground/docs/source-code-document/codebase-structure/2.codebase-walkthrough/src/utils/index.md
  system-contract-dapp-playground/package.json
  system-contract-dapp-playground/prerequisite-check/contracts-info/index.ts
  system-contract-dapp-playground/prerequisite-check/scripts/index.ts
  system-contract-dapp-playground/src/components/contract-interaction/exchange-rate/deployment/ExchangeRateDeployField.tsx
Labels: documentation, enhancement, P2, Tooling

#440 Adding unit tests for Solidity Crypto Units and Time Units
  contracts/solidity/units/cryptoUnits.sol
  contracts/solidity/units/timeUnits.sol
  test/constants.js
  test/solidity/units/cryptoUnits.js
  test/solidity/units/timeUnits.js
Labels: Limechain

#457 Adding tests for the Errors in Solidity
  contracts/solidity/errors/Errors.sol
  test/constants.js
  test/solidity/errors/errors.js
Labels: enhancement, P2

#442 Bumped up versions of the mirror node and consensus nodes in the CI w…
  .github/workflows/test-workflow.yml
Labels: enhancement, P3

#453 Adding tests for the Transactions in Solidity
  .gitignore
  contracts/solidity/transaction/MessageFrameAddresses.sol
  contracts/solidity/transaction/Transaction.sol
  test/constants.js
  test/solidity/transaction/transaction.js
Labels: enhancement, P1, Limechain, EVM

#469 Fix Solidity Github action
  .github/workflows/solidity-tests.yml
Labels: bug, P2

#467 feat: added new contract to demonstrate `new` keyword usage (#450)
  contracts/solidity/new/New.sol
  test/constants.js
  test/solidity/new/New.js
Labels: enhancement, P2, Tooling

#458 Tests for Address operations
  contracts/solidity/address/Address.sol
  contracts/solidity/address/Recipient.sol
  test/constants.js
  test/solidity/address/address.js
Labels: enhancement, P1, Limechain, EVM

#474 Adding tests for inheritance
  contracts/solidity/inhetitance/Base.sol
  contracts/solidity/inhetitance/Main.sol
  test/constants.js
  test/solidity/inheritance/inheritance.js
Labels: enhancement, P1, Limechain, EVM

#475 Adding tests for functions.
  contracts/solidity/functions/Functions.sol
  contracts/solidity/functions/FunctionsChild.sol
  contracts/solidity/functions/FunctionsParent.sol
  test/constants.js
  test/solidity/address/address.js
  test/solidity/concatenation/concatenation.js
  test/solidity/encoding/Encoding.js
  test/solidity/errors/errors.js
  test/solidity/functions/functions.js
  test/solidity/inheritance/inheritance.js
  test/solidity/new/New.js
  test/solidity/units/cryptoUnits.js
  test/solidity/units/timeUnits.js
Labels: enhancement, P1, Limechain, EVM

#484 feat: added new contract to showcase assembly address operations (#459)
  contracts/solidity/address/AssemblyAddress.sol
  test/constants.js
  test/solidity/address/AssemblyAddress.js
Labels: enhancement, P1, EVM, Tooling

#481 Adding tests for Arithmetic
  contracts/solidity/cryptomath/Arithmetic.sol
  test/constants.js
  test/solidity/cryptomath/CryptoMath.js
  test/solidity/cryptomath/arithmetic.js
  utils/helpers.js
Labels: enhancement, P1, Limechain, EVM

#497 Adding tests for the default values of all types in Solidity
  .gitignore
  contracts/solidity/defaults/Defaults.sol
  test/constants.js
  test/solidity/defaults/defaults.js
Labels: enhancement, P1, Limechain, EVM

#499 Adding tests for advance errors
  contracts/solidity/errors/Errors.sol
  contracts/solidity/errors/ErrorsExternal.sol
  test/constants.js
  test/solidity/errors/errors.js
Labels: enhancement, P1, Limechain, EVM

#509 feat: added PaymentChannel smart contract (#493)
  contracts/solidity/payment-channel/PaymentChannel.sol
  test/solidity/payment-channel/PaymentChannel.js
  test/solidity/payment-channel/helper.js
Labels: enhancement, P2, Tooling

#526 Adding TypeOps Solidity Test Coverage
  contracts/solidity/typeops/AnotherContract.sol
  contracts/solidity/typeops/MyInterface.sol
  contracts/solidity/typeops/TypeOps.sol
  test/constants.js
  test/solidity/typeops/TypeOps.js
Labels: enhancement

#523 feat: added modular solidity example contract (#494)
  contracts/solidity/modular/Token.sol
  test/solidity/modular/Token.js
Labels: enhancement, P2, EVM

#507 docs: added tutorial on installing foundry and forge to TEST_SETUP doc (#506)
  TEST_SETUP.md
Labels: enhancement, P2, Tooling

#521 feat: added math coverage solidity example contract (#511)
  contracts/yul/math-coverage/MatchCoverage.sol
  test/yul/math-coverage/MathCoverage.js
Labels: enhancement, P2, EVM, Tooling
