Repository hashgraph/hedera-smart-contracts, pull requests merged in 2024-06, with the labels that each got.

#800 feat: added cryptoTransfer to CryptoAllowance to showcase support in HIP906
  .github/workflows/tests.yml
  artifacts/contracts/hts-precompile/examples/crypto-allowance/cryptoAllowance.sol/CryptoAllowance.json
  artifacts/contracts/hts-precompile/examples/crypto-allowance/cryptoOwner.sol/CryptoOwner.json
  artifacts/contracts/hts-precompile/examples/crypto-allowance/cryptoOwner.sol/ICryptoAllowance.json
  contracts-abi/contracts/hts-precompile/IHRC632.sol/IHRC632.json
  contracts-abi/contracts/hts-precompile/examples/crypto-allowance/cryptoAllowance.sol/CryptoAllowance.json
  contracts-abi/contracts/hts-precompile/examples/crypto-allowance/cryptoOwner.sol/CryptoOwner.json
  contracts-abi/contracts/hts-precompile/examples/crypto-allowance/cryptoOwner.sol/ICryptoAllowance.json
  contracts-abi/contracts/hts-precompile/examples/hrc-632/HRC632Contract.sol/HRC719Contract.json
  contracts-abi/contracts/hts-precompile/examples/hrc-719/HRCContract.sol/HRC719Contract.json
  contracts/hts-precompile/HederaAccountService.sol
  contracts/hts-precompile/IHRC632.sol
  contracts/hts-precompile/examples/crypto-allowance/cryptoAllowance.sol
  contracts/hts-precompile/examples/crypto-allowance/cryptoOwner.sol
  test/constants.js
  test/hts-precompile/crypto-allowance/cryptoAllowance.js
  test/hts-precompile/ihrc-632/IHRC632.js
Labels: enhancement

#777 docs: Additional Slither AST note
  tools/analysis/slither/README.md
Labels: documentation

#816 feat: added example coverage for HIP-865
  artifacts/contracts/openzeppelin/ERC-20/ERC20Mock.sol/ERC20Mock.json
  artifacts/contracts/openzeppelin/ERC-721/ERC721Mock.sol/ERC721Mock.json
  contracts-abi/contracts/cancun/cancun-opcodes/CancunOpcodes.sol/CancunOpcodes.json
  contracts/cancun/cancun-opcodes/CancunOpcodes.sol
  foundry.toml
  hardhat.config.js
  test/cancun/cancun-opcodes/transientStorage.js
  test/constants.js
Labels: enhancement

#822 feat: added coverage for HIP-867
  contracts-abi/contracts/cancun/kzg-point-evaluation/KZGPointEvaluation.sol/KZGPointEvaluation.json
  contracts/cancun/kzg-point-evaluation/KZGPointEvaluation.sol
  test/cancun/kzg-point-evaluation/KZGPointEvaluation.js
  test/constants.js
Labels: enhancement

#827 fix: fixed ci failing test in System Dapp Contract
  .gitignore
  artifacts/contracts/precompile/exchange-rate/ExchangeRateMock.sol/ExchangeRateMock.json
  artifacts/contracts/precompile/exchange-rate/ExchangeRatePrecompile.sol/ExchangeRatePrecompile.json
  artifacts/contracts/precompile/exchange-rate/IExchangeRate.sol/IExchangeRate.json
  artifacts/contracts/precompile/exchange-rate/SelfFunding.sol/SelfFunding.json
  artifacts/contracts/precompile/hedera-token-service/IHRC719.sol/IHRC719.json
  artifacts/contracts/precompile/hedera-token-service/examples/erc-20/ERC20Contract.sol/ERC20Contract.json
  artifacts/contracts/precompile/hedera-token-service/examples/erc-721/ERC721Contract.sol/ERC721Contract.json
  artifacts/contracts/precompile/hedera-token-service/examples/hrc-719/HRC719Contract.sol/HRC719Contract.json
  artifacts/contracts/precompile/hedera-token-service/examples/token-create/TokenCreateContract.sol/TokenCreateContract.json
  artifacts/contracts/precompile/hedera-token-service/examples/token-create/TokenCreateCustom.sol/TokenCreateCustomContract.json
  artifacts/contracts/precompile/hedera-token-service/examples/token-manage/TokenManagementContract.sol/TokenManagementContract.json
  artifacts/contracts/precompile/hedera-token-service/examples/token-query/TokenQueryContract.sol/TokenQueryContract.json
  artifacts/contracts/precompile/hedera-token-service/examples/token-transfer/TokenTransferContract.sol/TokenTransferContract.json
  artifacts/contracts/precompile/pseudo-random-number-generator/IPrngSystemContract.sol/IPrngSystemContract.json
  artifacts/contracts/precompile/pseudo-random-number-generator/PrngSystemContract.sol/PrngSystemContract.json
Labels: bug
