Repository hashgraph/hedera-smart-contracts, pull requests merged in 2024-07, with the labels that each got.

#830 fix(slither): setting the correct path to the build in dc cofnig
  tools/analysis/slither/docker-compose.yaml
Labels: bug

#845 fix: renamed .github/README.md to ./github/workflows_documentation.md
  .github/workflows_documentation.md
Labels: enhancement

#851 docs: Bump 0.10.0-SNAPSHOT
  package-lock.json
  package.json
Labels: dependencies

#852 docs: Bump v0.9.0
  package-lock.json
  package.json
Labels: enhancement

#815 test: ecrecover evm compatibility
  contracts-abi/contracts/precompile/native/evm-compatibility-ecrecover/EcrecoverCheck.sol/EcrecoverCheck.json
  contracts/precompile/native/evm-compatibility-ecrecover/EcrecoverCheck.sol
  test/precompile/native/evm-compatibility-ecrecover/EcrecoverCheck.js
  test/precompile/native/evm-compatibility-ecrecover/utils.js
Labels: enhancement, EVM, ArianeLabs

#849 feat: added support for release automation
  .github/release.yml
  .github/scripts/check-pr.js
  .github/workflows/pr-label-milestone-check.yml
  .github/workflows/release-automation.yml
Labels: enhancement
