Repository hashgraph/hedera-smart-contracts, pull requests merged in 2024-12, with the labels that each got.

#1033 docs: added a design document outlining the ERC contract indexer
  .gitignore
  tools/erc-repository-indexer/docs/registry_design.md
Labels: documentation, enhancement, Design

#1043 chore: initialized a new NPM project for the indexer tool
  tools/erc-repository-indexer/erc-contract-indexer/example.env
  tools/erc-repository-indexer/erc-contract-indexer/jest.config.js
  tools/erc-repository-indexer/erc-contract-indexer/package-lock.json
  tools/erc-repository-indexer/erc-contract-indexer/package.json
  tools/erc-repository-indexer/erc-contract-indexer/tsconfig.json
Labels: enhancement

#1050 feat: added RegistryGenerator service class to export ERC token contracts
  tools/erc-repository-indexer/erc-contract-indexer/example.env
  tools/erc-repository-indexer/erc-contract-indexer/src/schemas/ERCRegistrySchemas.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/services/contractScanner.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/services/registryGenerator.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/utils/constants.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/utils/helper.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/services/registryGenerator.test.ts
Labels: enhancement

#1054 feat: added ConfigService service class to evaluate configurations.
  tools/erc-repository-indexer/erc-contract-indexer/example.env
  tools/erc-repository-indexer/erc-contract-indexer/src/services/byteCodeAnalyzer.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/services/config.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/services/contractScanner.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/utils/constants.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/utils/helper.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/services/byteCodeAnalyzer.test.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/services/config.test.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/services/contractScanner.test.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/utils/constants.ts
Labels: enhancement

#1057 feat: added an option for resolveStartingPoint() to fetch next pointer from disk
  tools/erc-repository-indexer/erc-contract-indexer/src/services/config.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/services/registryGenerator.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/utils/constants.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/services/config.test.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/services/registryGenerator.test.ts
Labels: enhancement

#1058 feat: added a main runner class as the entry point for the indexing tool
  tools/erc-repository-indexer/docs/registry_design.md
  tools/erc-repository-indexer/erc-contract-indexer/README.md
  tools/erc-repository-indexer/erc-contract-indexer/package.json
  tools/erc-repository-indexer/erc-contract-indexer/src/index.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/services/registryGenerator.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/utils/constants.ts
Labels: enhancement

#1053 chore: update codeowners
  .github/CODEOWNERS
Labels: enhancement

#1064 feat: added `getErcTokenInfo()` to retrieve detailed token information in the ERC Registry project.
  tools/erc-repository-indexer/erc-contract-indexer/package-lock.json
  tools/erc-repository-indexer/erc-contract-indexer/package.json
  tools/erc-repository-indexer/erc-contract-indexer/src/schemas/ERCRegistrySchemas.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/schemas/MirrorNodeSchemas.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/services/byteCodeAnalyzer.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/services/contractScanner.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/utils/constants.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/services/byteCodeAnalyzer.test.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/services/contractScanner.test.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/utils/constants.ts
Labels: enhancement

#1071 feat: allowed ERC registry indexing tool to target localnet
  tools/erc-repository-indexer/erc-contract-indexer/README.md
  tools/erc-repository-indexer/erc-contract-indexer/src/index.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/services/config.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/services/contractScanner.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/utils/constants.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/utils/helper.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/services/byteCodeAnalyzer.test.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/services/config.test.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/services/contractScanner.test.ts
Labels: enhancement

#1088 chore: update ERC Registry with latest ERC-20 and ERC-721 tokens on Hedera
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/previewnet/erc-20.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/previewnet/erc-721.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/previewnet/next-pointer.json
Labels: internal

#1091 chore: update ERC Registry with latest ERC-20 and ERC-721 tokens on Hedera
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/previewnet/erc-20.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/previewnet/erc-721.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/previewnet/next-pointer.json
Labels: internal

#1096 chore: update ERC Registry with latest ERC-20 and ERC-721 tokens on Hedera
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/previewnet/erc-20.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/previewnet/erc-721.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/previewnet/next-pointer.json
Labels: internal

#1097 chore: update ERC Registry with latest ERC-20 and ERC-721 tokens on Hedera
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/previewnet/erc-721.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/previewnet/next-pointer.json
Labels: internal

#1075 chore: added a list of files containing token information for ERC-20 and ERC-721 tokens on the Hedera networks
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/erc-20.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/erc-721.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/next-pointer.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/testnet/erc-20.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/testnet/erc-721.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/testnet/next-pointer.json
Labels: enhancement

#1106 chore(release): Bump versions for v0.12.0-SNAPSHOT
  package-lock.json
  package.json
Labels: process

#1100 chore: added a workflow script to enable the execution of the ERC registry project on dispatch
  .github/workflows/erc-registry-indexer.yml
  tools/erc-repository-indexer/erc-contract-indexer/README.md
Labels: internal

#1113 fix: allowed ERC Registry tool to handle optional ERC methods more gracefully
  tools/erc-repository-indexer/erc-contract-indexer/src/services/byteCodeAnalyzer.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/acceptance/acceptance.test.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/acceptance/contracts/erc-20/MinalmalERC20.sol
  tools/erc-repository-indexer/erc-contract-indexer/tests/acceptance/contracts/erc-20/MinimalERC20.json
  tools/erc-repository-indexer/erc-contract-indexer/tests/acceptance/contracts/erc-721/MinimalERC721.json
  tools/erc-repository-indexer/erc-contract-indexer/tests/acceptance/contracts/erc-721/MinimalERC721.sol
  tools/erc-repository-indexer/erc-contract-indexer/tests/acceptance/utils/helper.ts
Labels: enhancement

#1115 fix: replaced the SEVM library with a regex-based approach for the interface matching mechanism in ERC Registry project
  tools/erc-repository-indexer/docs/registry_design.md
  tools/erc-repository-indexer/erc-contract-indexer/package-lock.json
  tools/erc-repository-indexer/erc-contract-indexer/package.json
  tools/erc-repository-indexer/erc-contract-indexer/src/services/byteCodeAnalyzer.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/utils/constants.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/unit/services/byteCodeAnalyzer.test.ts
Labels: enhancement

#1121 fix: modified `isErc` for better performance in ERC Registry tool
  tools/erc-repository-indexer/erc-contract-indexer/package-lock.json
  tools/erc-repository-indexer/erc-contract-indexer/package.json
  tools/erc-repository-indexer/erc-contract-indexer/src/services/byteCodeAnalyzer.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/utils/constants.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/unit/services/byteCodeAnalyzer.test.ts
Labels: enhancement

#1122 chore: update the whole ERC Registry for mainnet
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/erc-20.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/erc-721.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/next-pointer.json
Labels: internal

#1123 chore: update the whole ERC Registry for testnet
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/testnet/erc-20.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/testnet/erc-721.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/testnet/next-pointer.json
Labels: internal
