Repository hashgraph/hedera-smart-contracts, pull requests merged in 2024-09, with the labels that each got.

#928 ci: Updating workflows/actions to use the step-security version.
  .github/workflows/solidity-tests.yml
  .github/workflows/test-workflow.yml
  .github/workflows/tests.yml
Labels: github_actions

#917 build(deps): [Snyk] Upgrade typescript from 5.1.6 to 5.5.4
  system-contract-dapp-playground/package-lock.json
  system-contract-dapp-playground/package.json
Labels: dependencies

#918 build(deps): [Snyk] Upgrade: react, react-dom
  system-contract-dapp-playground/package-lock.json
  system-contract-dapp-playground/package.json
Labels: dependencies

#926 build(deps): installed js-cookie
  system-contract-dapp-playground/package-lock.json
  system-contract-dapp-playground/package.json
Labels: dependencies

#905 test: add test coverage and example usage for HIP719 isAssociated()
  artifacts/contracts/system-contracts/hedera-token-service/IHRC719.sol/IHRC719.json
  artifacts/contracts/system-contracts/hedera-token-service/examples/hrc-719/HRC719Contract.sol/HRC719Contract.json
  contracts-abi/contracts/system-contracts/hedera-token-service/IHRC719.sol/IHRC719.json
  contracts-abi/contracts/system-contracts/hedera-token-service/examples/hrc-719/HRC719Contract.sol/HRC719Contract.json
  contracts/system-contracts/hedera-token-service/IHRC719.sol
  contracts/system-contracts/hedera-token-service/README.md
  contracts/system-contracts/hedera-token-service/examples/hrc-719/HRC719Contract.sol
  package-lock.json
  package.json
  test/constants.js
  test/foundry/mocks/hts-precompile/HederaFungibleToken.sol
  test/foundry/mocks/hts-precompile/HederaNonFungibleToken.sol
  test/foundry/mocks/hts-precompile/HtsSystemContractMock.sol
  test/hip-583/HIP583.js
  test/openzeppelin/ERC-721-Receiver/ERC721Receiver.js
  test/precompile/hedera-token-service/hrc-719/HRC719Contract.js
Labels: enhancement

#954 feat: fix migration flow
  .github/workflows/migration-testing.yml
Labels: bug

#956 ci: Adding further permissions to the manual-testing workflow as it was not running correctly.
  .github/workflows/manual-testing.yml
Labels: github_actions
