Repository hashgraph/hedera-smart-contracts, pull requests merged in 2024-10, with the labels that each got.

#911 feat: add new tests for HIP-1010
  artifacts/contracts/system-contracts/hedera-token-service/examples/token-create/TokenCreateContract.sol/TokenCreateContract.json
  artifacts/contracts/system-contracts/hedera-token-service/examples/token-create/TokenCreateCustom.sol/TokenCreateCustomContract.json
  artifacts/contracts/system-contracts/hedera-token-service/examples/token-manage/TokenManagementContract.sol/TokenManagementContract.json
  artifacts/contracts/system-contracts/hedera-token-service/examples/token-query/TokenQueryContract.sol/TokenQueryContract.json
  artifacts/contracts/system-contracts/hedera-token-service/examples/token-transfer/TokenTransferContract.sol/TokenTransferContract.json
  contracts-abi/contracts/system-contracts/hedera-token-service/IHederaTokenService.sol/IHederaTokenService.json
  contracts-abi/contracts/system-contracts/hedera-token-service/examples/token-create/TokenCreateCustom.sol/TokenCreateCustomContract.json
  contracts-abi/contracts/system-contracts/hedera-token-service/examples/token-manage/TokenManagementContract.sol/TokenManagementContract.json
  contracts-abi/contracts/system-contracts/hedera-token-service/examples/token-transfer/TokenTransferContract.sol/TokenTransferContract.json
  contracts/system-contracts/hedera-token-service/HederaTokenService.sol
  contracts/system-contracts/hedera-token-service/IHederaTokenService.sol
  contracts/system-contracts/hedera-token-service/examples/token-create/TokenCreateContract.sol
  contracts/system-contracts/hedera-token-service/examples/token-create/TokenCreateCustom.sol
  contracts/system-contracts/hedera-token-service/examples/token-manage/TokenManagementContract.sol
  contracts/system-contracts/hedera-token-service/examples/token-transfer/TokenTransferContract.sol
  package-lock.json
  package.json
  test/hip-583/HIP583.js
  test/precompile/hedera-token-service/erc-20/ERC20Contract.js
  test/precompile/hedera-token-service/erc-20/IERC20.js
  test/precompile/hedera-token-service/token-create/tokenCreateContract.js
  test/precompile/hedera-token-service/token-managment/tokenManagmentContract.js
  test/precompile/hedera-token-service/utils.js
Labels: enhancement

#960 feat: gas comparison for verifying a BLS signatures using G1 for public key
  contracts-abi/contracts/bls-bn254-signatures/BlsBn254.sol/BlsBn254.json
  contracts/bls-bn254-signatures/BlsBn254.sol
  package-lock.json
  package.json
  test/bls-bn254-signatures/README.md
  test/bls-bn254-signatures/bls-bn254-signatures.js
  test/bls-bn254-signatures/blsHelper.js
  test/constants.js
Labels: enhancement

#969 ci: Update Permissions on smart-contracts workflows to update main
  .github/CODEOWNERS
  .github/workflows/release-automation.yml
Labels: enhancement

#976 fix: updated release automation workflow
  .github/workflows/release-automation.yml
Labels: enhancement

#975 chore(release): Bump versions for v0.11.0-SNAPSHOT
  package-lock.json
  package.json
Labels: process

#977 chore: cherry picked #969 and #976 to release/0.10
  .github/CODEOWNERS
  .github/workflows/release-automation.yml
Labels: github_actions

#984 test: added test coverage to confirm key alias remain the same after key rotations
  test/network/key-rotation.js
Labels: enhancement

#982 feat: Skip issue matching for snyk and dependabot PRs.
  .github/scripts/check-pr.js
Labels: enhancement

#991 ci: Add "contents" persmission and add hardened runner step
  .github/workflows/dapp-playground-workflow.yml
  .github/workflows/flow-pr-title-check.yml
  .github/workflows/foundry_test.yml
  .github/workflows/migration-testing.yml
  .github/workflows/opcode-logger-testing.yml
  .github/workflows/pr-label-milestone-check.yml
  .github/workflows/release-production.yml
  .github/workflows/solidity-tests.yml
  .github/workflows/test-workflow.yml
  .github/workflows/tests.yml
Labels: github_actions

#986 ci: Updating one of the actions to fix issues with inputs.
  .github/workflows/test-workflow.yml
Labels: github_actions

#1000 fix: skipped title check CI job for forked PRs
  .github/workflows/flow-pr-title-check.yml
Labels: internal

#997 test: added E2E coverage for `isAuthorizedRaw()` in HIP-632.
  contracts-abi/contracts/system-contracts/hedera-account-service/examples/crypto-allowance/cryptoAllowance.sol/CryptoAllowance.json
  contracts/system-contracts/hedera-account-service/HederaAccountService.sol
  contracts/system-contracts/hedera-account-service/examples/crypto-allowance/cryptoAllowance.sol
  test/system-contracts/hedera-account-service/crypto-allowance/cryptoAllowance.js
Labels: enhancement
