Repository hashgraph/hedera-smart-contracts, pull requests merged in 2025-01, with the labels that each got.

#1138 fix: updated .github/release.yaml to include internal and github_action labeled PRs
  .github/release.yml
Labels: internal

#1143 chore: updated erc-registry workflow to create PR to MNE repo
  .github/workflows/erc-registry-indexer.yml
Labels: internal

#1132 feat: added support for ERC Registry tool to dynamically configure the number of contracts to scan per operation
  .github/workflows/erc-registry-indexer.yml
  tools/erc-repository-indexer/docs/registry_design.md
  tools/erc-repository-indexer/erc-contract-indexer/README.md
  tools/erc-repository-indexer/erc-contract-indexer/example.env
  tools/erc-repository-indexer/erc-contract-indexer/src/runner.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/services/config.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/services/contractScanner.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/utils/helper.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/unit/services/byteCodeAnalyzer.test.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/unit/services/config.test.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/unit/services/contractScanner.test.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/unit/utils/helper.spec.ts
Labels: enhancement

#1153 ci: fixed check for forked repository on PR
  .github/workflows/flow-pr-title-check.yml
Labels: internal

#1166 feat: implemented ERC-1155 detection support in the ERC Registry tool
  tools/erc-repository-indexer/erc-contract-indexer/README.md
  tools/erc-repository-indexer/erc-contract-indexer/src/runner.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/schemas/ERCRegistrySchemas.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/services/byteCodeAnalyzer.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/services/registryGenerator.ts
  tools/erc-repository-indexer/erc-contract-indexer/src/utils/constants.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/acceptance/acceptance.test.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/acceptance/contracts/erc-1155/ERC1155Mock.json
  tools/erc-repository-indexer/erc-contract-indexer/tests/acceptance/contracts/erc-1155/ERC1155Mock.sol
  tools/erc-repository-indexer/erc-contract-indexer/tests/acceptance/utils/constants.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/acceptance/utils/helper.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/unit/services/byteCodeAnalyzer.test.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/unit/services/registryGenerator.test.ts
  tools/erc-repository-indexer/erc-contract-indexer/tests/unit/utils/constants.ts
Labels: enhancement

#1168 ci: added CI workflow for ERC registry tool
  .github/workflows/erc-registry-test.yml
  tools/erc-repository-indexer/erc-contract-indexer/local.env
Labels: internal

#1169 chore: fix CODEOWNERS file
  .github/CODEOWNERS
Labels: github_actions

#1176 chore: added ERC-1155 to ERC Registry Indexer workflow
  .github/workflows/erc-registry-indexer.yml
Labels: internal

#1177 feat: adds CI workflows for HIP904 tests
  .github/workflows/manual-testing.yml
  .github/workflows/tests.yml
Labels: internal

#1125 feat: adds example HRC904 contracts + new methods to HTS contract
  artifacts/contracts/system-contracts/hedera-token-service/examples/hrc-904/Airdrop.sol/Airdrop.json
  artifacts/contracts/system-contracts/hedera-token-service/examples/hrc-904/CancelAirdrop.sol/CancelAirdrop.json
  artifacts/contracts/system-contracts/hedera-token-service/examples/hrc-904/ClaimAirdrop.sol/ClaimAirdrop.json
  artifacts/contracts/system-contracts/hedera-token-service/examples/hrc-904/HRC904Contract.sol/HRC904Contract.json
  artifacts/contracts/system-contracts/hedera-token-service/examples/hrc-904/TokenReject.sol/TokenReject.json
  artifacts/contracts/system-contracts/hedera-token-service/examples/token-create/TokenCreateContract.sol/TokenCreateContract.json
  artifacts/contracts/system-contracts/hedera-token-service/examples/token-create/TokenCreateCustom.sol/TokenCreateCustomContract.json
  artifacts/contracts/system-contracts/hedera-token-service/examples/token-manage/TokenManagementContract.sol/TokenManagementContract.json
  artifacts/contracts/system-contracts/hedera-token-service/examples/token-query/TokenQueryContract.sol/TokenQueryContract.json
  artifacts/contracts/system-contracts/hedera-token-service/examples/token-transfer/TokenTransferContract.sol/TokenTransferContract.json
  contracts-abi/contracts/system-contracts/hedera-token-service/examples/hrc-904/Airdrop.sol/Airdrop.json
  contracts-abi/contracts/system-contracts/hedera-token-service/examples/hrc-904/CancelAirdrop.sol/CancelAirdrop.json
  contracts-abi/contracts/system-contracts/hedera-token-service/examples/hrc-904/ClaimAirdrop.sol/ClaimAirdrop.json
  contracts-abi/contracts/system-contracts/hedera-token-service/examples/hrc-904/HRC904Contract.sol/HRC904Contract.json
  contracts-abi/contracts/system-contracts/hedera-token-service/examples/hrc-904/TokenReject.sol/TokenReject.json
  contracts/system-contracts/hedera-token-service/HederaTokenService.sol
  contracts/system-contracts/hedera-token-service/examples/hrc-904/Airdrop.sol
  contracts/system-contracts/hedera-token-service/examples/hrc-904/CancelAirdrop.sol
  contracts/system-contracts/hedera-token-service/examples/hrc-904/ClaimAirdrop.sol
  contracts/system-contracts/hedera-token-service/examples/hrc-904/HRC904Contract.sol
  contracts/system-contracts/hedera-token-service/examples/hrc-904/TokenReject.sol
Labels: enhancement

#1179 chore: update ERC Registry with latest ERC-20, ERC-721, and ERC-1155 tokens on Hedera mainnet
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/erc-1155.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/erc-20.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/erc-721.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/next-pointer.json
Labels: internal

#1180 chore: update ERC Registry with latest ERC-20, ERC-721, and ERC-1155 tokens on Hedera testnet
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/testnet/erc-1155.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/testnet/next-pointer.json
Labels: internal

#1142 test: validate contract and admin key in hollow account finalized as contract
  test/contract-admin-id/contractAdminId.js
  test/system-contracts/hedera-token-service/utils.js
Labels: enhancement

#1184 feat: migrate LZ contracts from the relay repo
  lib/layer-zero/ExampleHTSConnector.sol
  lib/layer-zero/ExampleHTSConnectorExistingToken.sol
  lib/layer-zero/ExampleOApp.sol
  lib/layer-zero/ExampleOFT.sol
  lib/layer-zero/ExampleOFTAdapter.sol
  lib/layer-zero/ExampleONFT.sol
  lib/layer-zero/ExampleONFTAdapter.sol
  lib/layer-zero/HTSConnector.sol
  lib/layer-zero/HTSConnectorExistingToken.sol
  lib/layer-zero/hts/HederaTokenService.sol
  lib/layer-zero/hts/IHederaTokenService.sol
  lib/layer-zero/hts/KeyHelper.sol
Labels: enhancement

#1206 fix: make tests dependency explicit
  test/openzeppelin/ERC-20/ERC20.js
Labels: internal

#1204 feat: adds clarification for tokenSupplyType parameter wherever it's passed
  artifacts/contracts/system-contracts/hedera-token-service/examples/token-create/TokenCreateContract.sol/TokenCreateContract.json
  artifacts/contracts/system-contracts/hedera-token-service/examples/token-create/TokenCreateCustom.sol/TokenCreateCustomContract.json
  contracts/system-contracts/hedera-token-service/examples/token-create/TokenCreateContract.sol
  contracts/system-contracts/hedera-token-service/examples/token-create/TokenCreateCustom.sol
  contracts/system-contracts/hedera-token-service/safe-hts/SafeOperations.sol
  lib/layer-zero/HTSConnector.sol
Labels: internal

#1210 feat: address WHBAR audit comments
  contracts-abi/contracts/wrapped-tokens/WHBAR.sol/WHBAR.json
  contracts/wrapped-tokens/README.md
  contracts/wrapped-tokens/WHBAR.sol
  test/wrapped-tokens/WHBAR.js
Labels: enhancement

#1212 chore: add schedule service system contract definition files
  contracts/system-contracts/hedera-schedule-service/HederaScheduleService.sol
  contracts/system-contracts/hedera-schedule-service/IHRC755.sol
  contracts/system-contracts/hedera-schedule-service/IHRC755ScheduleFacade.sol
  contracts/system-contracts/hedera-schedule-service/IHRC756.sol
  contracts/system-contracts/hedera-schedule-service/IHederaScheduleService.sol
  contracts/system-contracts/hedera-schedule-service/README.md
Labels: enhancement

#1216 feat: add warning into lz contracts readme
  lib/layer-zero/README.md
Labels: enhancement
