Repository hashgraph/hedera-smart-contracts, pull requests merged in 2025-02, with the labels that each got.

#875 test: extended coverage for debug_traceTransaction with opcode logger…
  contracts-abi/contracts/solidity/opcode-logger/OpcodeLogger.sol/OpcodeLogger.json
  contracts-abi/contracts/solidity/opcode-logger/TokenCreateOpcodeLogger.sol/TokenCreateOpcodeLogger.json
  contracts/solidity/opcode-logger/OpcodeLogger.sol
  contracts/solidity/opcode-logger/TokenCreateOpcodeLogger.sol
  test/constants.js
  test/solidity/opcode-logger/opcodeLogger.js
  test/utils.js
Labels: enhancement, Limechain

#1198 feat: adds tests that verify IHRC904 rejectTokens targeted to an EOA are functional when called by a contract
  test/constants.js
  test/system-contracts/hedera-token-service/hrc-904/TokenRejectContract.js
  test/system-contracts/hedera-token-service/utils.js
Labels: enhancement

#1186 feat: Adds tests that verify IHRC904Proxy methods targeted to an EOA are functional when called by EOA
  artifacts/contracts/openzeppelin/ERC-20/ERC20Mock.sol/OZERC20Mock.json
  artifacts/contracts/openzeppelin/ERC-721/ERC721Mock.sol/OZERC721Mock.json
  artifacts/contracts/system-contracts/hedera-token-service/examples/erc-20/ERC20Contract.sol/ERC20Contract.json
  artifacts/contracts/system-contracts/hedera-token-service/examples/erc-721/ERC721Contract.sol/ERC721Contract.json
  artifacts/contracts/system-contracts/hedera-token-service/examples/hrc-904/HRC904Contract.sol/HRC904Contract.json
  artifacts/contracts/system-contracts/hedera-token-service/examples/token-manage/TokenManagementContract.sol/TokenManagementContract.json
  contracts-abi/contracts/system-contracts/hedera-token-service/examples/hrc-904/HRC904Contract.sol/HRC904Contract.json
  contracts/system-contracts/hedera-token-service/examples/hrc-904/HRC904Contract.sol
  test/constants.js
  test/system-contracts/hedera-token-service/hrc-904/IHRC904ProxyTests.js
  test/system-contracts/hedera-token-service/utils.js
Labels: enhancement

#1192 feat: added test coverage of CancelAirdrop.sol
  artifacts/contracts/system-contracts/hedera-token-service/examples/hrc-904/CancelAirdrop.sol/CancelAirdrop.json
  contracts-abi/contracts/system-contracts/hedera-token-service/examples/hrc-904/CancelAirdrop.sol/CancelAirdrop.json
  contracts/system-contracts/hedera-token-service/examples/hrc-904/CancelAirdrop.sol
  test/constants.js
  test/system-contracts/hedera-token-service/hrc-904/CancelAirdropContract.js
  test/system-contracts/hedera-token-service/utils.js
Labels: enhancement

#703 test: extend the coverage of account nonce discrepancies tests
  contracts-abi/contracts/discrepancies/nonce/InternalCallee.sol/InternalCallee.json
  contracts-abi/contracts/discrepancies/nonce/InternalCallee.sol/Sample.json
  contracts/discrepancies/nonce/InternalCallee.sol
  test/discrepancies/Nonce.js
  test/system-contracts/hedera-token-service/utils.js
Labels: enhancement

#1220 feat: automatic update of `HederaResponseCodes.sol`
  .github/workflows/update-hedera-response-codes.yml
  contracts/system-contracts/HederaResponseCodes.sol
  package-lock.json
  package.json
  scripts/hedera-response-codes-protobuf-parser.js
Labels: enhancement

#1242 feat: add require check post transfer on WHBAR.sol
  contracts-abi/contracts/solidity/new/New.sol/Target.json
  contracts-abi/contracts/wrapped-tokens/WHBAR.sol/WHBAR.json
  contracts/solidity/new/New.sol
  contracts/wrapped-tokens/README.md
  contracts/wrapped-tokens/WHBAR.sol
  test/constants.js
  test/solidity/new/New.js
  test/wrapped-tokens/WHBAR.js
Labels: enhancement

#1245 feat: Removes skipped test from AirdropContract.js
  package-lock.json
  package.json
  test/system-contracts/hedera-token-service/hrc-904/AirdropContract.js
  test/system-contracts/hedera-token-service/hrc-904/CancelAirdropContract.js
Labels: enhancement

#1249 feat: add HIP-755 test coverage
  .github/workflows/tests.yml
  contracts-abi/contracts/system-contracts/hedera-schedule-service/IHRC755.sol/IHRC755.json
  contracts-abi/contracts/system-contracts/hedera-schedule-service/IHRC755ScheduleFacade.sol/IHRC755ScheduleFacade.json
  contracts-abi/contracts/system-contracts/hedera-schedule-service/IHRC756.sol/IHRC756.json
  contracts-abi/contracts/system-contracts/hedera-schedule-service/IHederaScheduleService.sol/IHederaScheduleService.json
  contracts-abi/contracts/system-contracts/hedera-schedule-service/examples/IHRC-755/HRC755Contract.sol/HRC755Contract.json
  contracts/system-contracts/hedera-schedule-service/examples/IHRC-755/HRC755Contract.sol
  test/system-contracts/hedera-schedule-service/hrc-755/HIP755.js
  test/system-contracts/hedera-token-service/utils.js
Labels: enhancement

#1262 chore: update ERC Registry with latest ERC-20, ERC-721, and ERC-1155 tokens on Hedera testnet
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/testnet/erc-1155.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/testnet/erc-20.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/testnet/erc-721.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/testnet/next-pointer.json
Labels: internal

#1263 chore: update ERC Registry with latest ERC-20, ERC-721, and ERC-1155 tokens on Hedera mainnet
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/erc-1155.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/erc-20.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/erc-721.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/next-pointer.json
Labels: internal
