Repository hashgraph/hedera-smart-contracts, pull requests merged in 2025-04, with the labels that each got.

#1308 chore: update ERC Registry with latest ERC-20, ERC-721, and ERC-1155 tokens on Hedera mainnet
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/erc-1155.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/erc-20.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/erc-721.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/next-pointer.json
Labels: internal

#1307 chore: update ERC Registry with latest ERC-20, ERC-721, and ERC-1155 tokens on Hedera testnet
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/testnet/erc-1155.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/testnet/erc-20.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/testnet/erc-721.json
  tools/erc-repository-indexer/erc-contract-indexer/erc-registry/testnet/next-pointer.json
Labels: internal

#1295 feat: remove skip flag from tests
  package-lock.json
  package.json
  test/system-contracts/hedera-account-service/ihrc-632/aliasAccountUtility.js
  test/system-contracts/hedera-token-service/hrc-904/AirdropContract.js
  test/system-contracts/hedera-token-service/hrc-904/CancelAirdropContract.js
  test/system-contracts/hedera-token-service/hrc-904/ClaimAirdropContract.js
  test/system-contracts/hedera-token-service/hrc-904/IHRC904ProxyTests.js
  test/system-contracts/hedera-token-service/utils.js
Labels: enhancement

#1323 fix: Update flow-pr-title-check.yml
  .github/workflows/flow-pr-title-check.yml
Labels: bug, dependencies

#1330 feat: split up hip 904 tests into 3 batches
  .github/workflows/manual-testing.yml
  .github/workflows/tests.yml
  test/system-contracts/hedera-token-service/hrc-904/AirdropContract.js
  test/system-contracts/hedera-token-service/hrc-904/CancelAirdropContract.js
  test/system-contracts/hedera-token-service/hrc-904/ClaimAirdropContract.js
  test/system-contracts/hedera-token-service/hrc-904/IHRC904ProxyTests.js
  test/system-contracts/hedera-token-service/hrc-904/TokenRejectContract.js
Labels: enhancement

#1313 fix: updated ERC Registry workflow to reference the MNE repo under hiero-ledger organziation
  .github/workflows/erc-registry-indexer.yml
Labels: internal
